package pipeline

import (
	"fmt"
	"strings"
)

const generatedYAMLHeader = "# Generated by neckbeard — do not edit. Regeneration refuses modified files;\n# change neckbeard.yaml or app-profile.yaml and re-run plan + scaffold.\n# The test hook (.neckbeard/hooks/test.sh) is yours and never regenerated.\n"

// RenderGitHubCI emits the app workflow: test on every PR/push; build, scan, and
// push (immutable tag, dev registry) on the default branch. Promotion moves the
// digest, never rebuilds (DESIGN §11.2). Cloud federation is OIDC-only (§10.1).
func RenderGitHubCI(m Model) []byte {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	w("%s", generatedYAMLHeader)
	w("name: neckbeard-ci")
	w("")
	w("on:")
	w("  pull_request:")
	w("  push:")
	w("    branches: [%s]", m.DefaultBranch)
	w("")
	w("permissions:")
	w("  contents: read")
	w("")
	w("jobs:")
	w("  test:")
	w("    runs-on: ubuntu-latest")
	w("    steps:")
	w("      - uses: actions/checkout@v4")
	w("      - name: Run test hook")
	w("        run: ./.neckbeard/hooks/test.sh")
	w("")
	w("  build:")
	w("    # Build once on %s; every environment runs this image by digest.", m.DefaultBranch)
	w("    if: github.event_name == 'push' && github.ref == 'refs/heads/%s'", m.DefaultBranch)
	w("    needs: [test]")
	w("    runs-on: ubuntu-latest")
	w("    environment: dev")
	w("    permissions:")
	w("      contents: read")
	w("      id-token: write # OIDC federation — no static cloud keys (DESIGN §10.1)")
	w("    env:")
	w("      REGISTRY: ${{ vars.%s_DEV }}", VarRegistry)
	w("    steps:")
	w("      - uses: actions/checkout@v4")
	w("      - name: Check bootstrap")
	w("        id: bootstrap")
	w("        run: |")
	w("          if [ -z \"$REGISTRY\" ]; then")
	w("            echo \"::warning::%s_DEV is not set (bootstrap pending, see docs/bootstrap.md) — build runs, push is skipped\"", VarRegistry)
	w("            echo \"push=false\" >> \"$GITHUB_OUTPUT\"")
	w("          else")
	w("            echo \"push=true\" >> \"$GITHUB_OUTPUT\"")
	w("          fi")
	githubFederation(w, m, "dev", "apply", "steps.bootstrap.outputs.push == 'true'")
	w("      - name: Build image")
	w("        run: docker build -f %s -t \"neckbeard-build:${GITHUB_SHA}\" .", shellQuote(m.Dockerfile))
	w("      - name: Scan image (HIGH/CRITICAL block the merge gate)")
	w("        run: |")
	w("          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \\")
	w("            aquasec/trivy image --severity HIGH,CRITICAL --exit-code 1 \"neckbeard-build:${GITHUB_SHA}\"")
	w("      - name: Push (immutable tag; promotion moves digests, never rebuilds)")
	w("        if: steps.bootstrap.outputs.push == 'true'")
	w("        run: |")
	for _, line := range registryLogin(m) {
		w("          %s", line)
	}
	w("          docker tag \"neckbeard-build:${GITHUB_SHA}\" \"${REGISTRY}:${GITHUB_SHA}\"")
	w("          docker push \"${REGISTRY}:${GITHUB_SHA}\"")
	w("          echo \"Pushed digest:\"")
	w("          docker inspect --format='{{index .RepoDigests 0}}' \"${REGISTRY}:${GITHUB_SHA}\"")
	return []byte(b.String())
}

// RenderGitHubInfra emits the infra workflow: per-env validate + plan on PRs,
// apply on the default branch. prd binds to the "prd" environment (§11.3).
func RenderGitHubInfra(m Model) []byte {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	w("%s", generatedYAMLHeader)
	w("name: neckbeard-infra")
	w("")
	w("on:")
	w("  pull_request:")
	w("    paths: [\"infra/**\", \".neckbeard/catalog/**\", \".checkov.yaml\"]")
	w("  push:")
	w("    branches: [%s]", m.DefaultBranch)
	w("    paths: [\"infra/**\", \".neckbeard/catalog/**\", \".checkov.yaml\"]")
	w("")
	w("permissions:")
	w("  contents: read")
	w("")
	w("jobs:")
	w("  policy:")
	w("    # The policy gate (DESIGN §10.1): checkov over every env root, honoring")
	w("    # the generated .checkov.yaml (every skip carries a written reason).")
	w("    runs-on: ubuntu-latest")
	w("    steps:")
	w("      - uses: actions/checkout@v4")
	w("      - name: Install checkov")
	w("        run: pipx install checkov==3.3.10 # pinned: the .checkov.yaml skips are curated against this version")
	w("      - name: Policy gate")
	w("        run: |")
	for _, env := range m.Envs {
		w("          checkov -d infra/envs/%s --quiet --compact --framework terraform --config-file .checkov.yaml", env)
		w("          checkov -d infra/bootstrap/%s --quiet --compact --framework terraform --config-file .checkov.yaml", env)
	}
	w("")
	for _, env := range m.Envs {
		w("  infra-%s:", env)
		w("    needs: [policy]")
		w("    runs-on: ubuntu-latest")
		w("    environment: %s", env)
		w("    permissions:")
		w("      contents: read")
		w("      id-token: write")
		if m.Cloud == "azure" {
			envU := strings.ToUpper(env)
			w("    env:")
			w("      ARM_USE_OIDC: \"true\"")
			w("      ARM_TENANT_ID: ${{ vars.%s }}", VarAzureTenant)
			w("      ARM_SUBSCRIPTION_ID: ${{ vars.%s_%s }}", VarAzureSub, envU)
			w("      # plan client on PRs, apply client on %s", m.DefaultBranch)
			w("      ARM_CLIENT_ID: ${{ github.event_name == 'push' && vars.%s_%s || vars.%s_%s }}", VarAzureApplyClient, envU, VarAzurePlanClient, envU)
		}
		w("    steps:")
		w("      - uses: actions/checkout@v4")
		w("      - uses: opentofu/setup-opentofu@v1")
		w("        with:")
		w("          tofu_version: %s # pinned by the blueprint", m.TofuVersion)
		w("      - name: Static validate (V0)")
		w("        run: |")
		w("          tofu -chdir=infra/envs/%s init -backend=false -input=false", env)
		w("          tofu -chdir=infra/envs/%s validate", env)
		if m.Cloud != "azure" { // azure federates via the ARM_ env above
			githubFederation(w, m, env, "auto", fmt.Sprintf("vars.%s != ''", GateVar(m.Cloud, env)))
		}
		w("      - name: Plan, and apply on %s (V1; needs bootstrap, see docs/bootstrap.md)", m.DefaultBranch)
		w("        run: |")
		w("          if [ ! -f infra/envs/%s/backend.hcl ] || [ -z \"${{ vars.%s }}\" ]; then", env, GateVar(m.Cloud, env))
		w("            echo \"::warning::bootstrap pending for %s (backend.hcl or CI variables missing) — validate-only run; plan/apply NOT EXERCISED\"", env)
		w("            exit 0")
		w("          fi")
		w("          tofu -chdir=infra/envs/%s init -reconfigure -input=false -backend-config=backend.hcl", env)
		w("          tofu -chdir=infra/envs/%s plan -input=false -out=tfplan", env)
		w("          if [ \"$GITHUB_EVENT_NAME\" = \"push\" ]; then")
		w("            tofu -chdir=infra/envs/%s apply -input=false tfplan", env)
		w("          fi")
		w("")
	}
	return []byte(strings.TrimRight(b.String(), "\n") + "\n")
}

// githubFederation writes the OIDC credential step for the cloud. roleKind
// "apply" pins the apply identity; "auto" selects plan on PRs, apply on pushes.
func githubFederation(w func(string, ...any), m Model, env, roleKind, ifExpr string) {
	envU := strings.ToUpper(env)
	switch m.Cloud {
	case "gcp":
		sa := fmt.Sprintf("${{ vars.%s_%s }}", VarGCPApplySA, envU)
		if roleKind == "auto" {
			sa = fmt.Sprintf("${{ github.event_name == 'push' && vars.%s_%s || vars.%s_%s }}", VarGCPApplySA, envU, VarGCPPlanSA, envU)
		}
		w("      - name: Federate to GCP (%s) — workload identity, no keys", env)
		w("        if: %s", ifExpr)
		w("        uses: google-github-actions/auth@v2")
		w("        with:")
		w("          workload_identity_provider: ${{ vars.%s_%s }}", VarGCPProvider, envU)
		w("          service_account: %s", sa)
	case "azure":
		w("      - name: Federate to Azure (%s)", env)
		w("        if: %s", ifExpr)
		w("        uses: azure/login@v2")
		w("        with:")
		w("          client-id: ${{ vars.%s_%s }}", VarAzureApplyClient, envU)
		w("          tenant-id: ${{ vars.%s }}", VarAzureTenant)
		w("          subscription-id: ${{ vars.%s_%s }}", VarAzureSub, envU)
	default: // aws
		role := fmt.Sprintf("${{ vars.%s_%s }}", VarApplyRole, envU)
		if roleKind == "auto" {
			role = fmt.Sprintf("${{ github.event_name == 'push' && vars.%s_%s || vars.%s_%s }}", VarApplyRole, envU, VarPlanRole, envU)
		}
		w("      - name: Federate to AWS (%s) — plan role on PRs, apply role on pushes", env)
		w("        if: %s", ifExpr)
		w("        uses: aws-actions/configure-aws-credentials@v4")
		w("        with:")
		w("          role-to-assume: %s", role)
		w("          aws-region: %s", m.Region)
	}
}

// registryLogin emits the docker-login lines for the cloud's registry.
func registryLogin(m Model) []string {
	switch m.Cloud {
	case "gcp":
		return []string{
			`gcloud auth configure-docker "${REGISTRY%%/*}" --quiet`,
		}
	case "azure":
		return []string{
			`az acr login --name "${REGISTRY%%.*}"`,
		}
	default: // aws
		return []string{
			fmt.Sprintf(`aws ecr get-login-password --region %s | docker login --username AWS --password-stdin "${REGISTRY%%%%/*}"`, m.Region),
		}
	}
}
