package render

import (
	"fmt"
	"strings"

	"github.com/bealesh/neckbeard/core/blueprint"
	"github.com/bealesh/neckbeard/core/ownership"
)

// bootstrapFiles renders infra/bootstrap/<env>/ — the one root a human applies
// with elevated credentials, once per environment (DESIGN §10.3): state backend,
// CI OIDC federation, plan/apply identities. These roots keep LOCAL state; the
// runbook says so and treats the state files as operator artifacts.
func bootstrapFiles(bp *blueprint.Blueprint, l lane, opts Options) []ownership.File {
	var files []ownership.File
	for _, env := range bp.Environments {
		dir := "infra/bootstrap/" + env.Name
		files = append(files,
			ownership.File{Path: dir + "/providers.tf", Content: l.providers(bp, env), Owner: ownership.OwnerGenerated},
			ownership.File{Path: dir + "/main.tf", Content: bootstrapMainTF(bp, env, opts), Owner: ownership.OwnerGenerated},
			ownership.File{Path: dir + "/outputs.tf", Content: bootstrapOutputsTF(), Owner: ownership.OwnerGenerated},
		)
	}
	files = append(files, ownership.File{Path: "docs/bootstrap.md", Content: bootstrapRunbook(bp), Owner: ownership.OwnerGenerated})
	return files
}

func bootstrapMainTF(bp *blueprint.Blueprint, env blueprint.Environment, opts Options) []byte {
	mod := blueprint.ModuleUsage{Source: "catalog/" + bp.Cloud + "/bootstrap"}
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Bootstrap keeps LOCAL state on purpose (it creates the backend everything\n# else uses); treat terraform.tfstate here as an operator artifact — see\n# docs/bootstrap.md.\n\n")
	lines := []kv{
		{"source", fmt.Sprintf("%q", moduleSource(opts, bp, mod))},
		{"name_prefix", fmt.Sprintf("%q", fmt.Sprintf("%s-%s-%s", bp.Org, bp.App, env.Name))},
		{"region", fmt.Sprintf("%q", bp.Region)},
		{"environment", fmt.Sprintf("%q", env.Name)},
		{"vcs", fmt.Sprintf("%q", bp.VCS)},
		{"repo", fmt.Sprintf("%q", bp.Repo)},
	}
	fmt.Fprintf(&b, "module \"bootstrap\" {\n%s}\n", alignKV(lines, 2))
	return []byte(b.String())
}

func bootstrapOutputsTF() []byte {
	return []byte(generatedHeader + `output "backend_hcl" {
  description = "Write to infra/envs/<env>/backend.hcl and commit it."
  value       = module.bootstrap.backend_hcl
}

output "ci_variables" {
  description = "Set these as CI variables (docs/bootstrap.md has the exact commands)."
  value       = module.bootstrap.ci_variables
}
`)
}

func bootstrapRunbook(bp *blueprint.Blueprint) []byte {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	login := map[string]string{
		"aws":   "credentials for THAT environment's AWS account exported (e.g. `aws sso login` / env vars); admin-equivalent IAM",
		"gcp":   "`gcloud auth application-default login` against THAT environment's project; Owner-equivalent IAM",
		"azure": "`az login` with rights on THAT environment's subscription: Owner (role assignments are created) plus Entra Application Developer (app registrations)",
	}[bp.Cloud]
	varCmd := "gh variable set"
	if bp.VCS == "gitlab" {
		varCmd = "glab variable set"
	}

	w("# Bootstrap runbook — %s", bp.App)
	w("")
	w("> Generated by neckbeard. One-time, per environment, run by a human with")
	w("> elevated credentials (DESIGN §10.3). Everything after this runs on federated")
	w("> CI identities — no static cloud keys, ever.")
	w("")
	w("Repeat the steps below once per environment (dev, stg, prd).")
	w("")
	w("## 0. Credentials")
	w("")
	w("You need %s.", login)
	w("")
	w("## 1. Apply the bootstrap root")
	w("")
	w("```sh")
	w("tofu -chdir=infra/bootstrap/<env> init")
	w("tofu -chdir=infra/bootstrap/<env> apply")
	w("```")
	w("")
	w("This root keeps **local state** (it creates the backend everything else uses).")
	w("Keep `infra/bootstrap/<env>/terraform.tfstate` safe like a credential: it is the")
	w("recovery handle for the backend and CI trust. Re-running apply is idempotent;")
	w("after a partial failure, re-run — it continues rather than recreating.")
	w("")
	w("## 2. Wire the environment backend")
	w("")
	w("```sh")
	w("tofu -chdir=infra/bootstrap/<env> output -raw backend_hcl > infra/envs/<env>/backend.hcl")
	w("git add infra/envs/<env>/backend.hcl && git commit -m 'bootstrap: <env> backend'")
	w("```")
	w("")
	w("## 3. Set the CI variables")
	w("")
	w("The pipelines read these names; the values come from the bootstrap outputs:")
	w("")
	w("```sh")
	w("tofu -chdir=infra/bootstrap/<env> output -json ci_variables \\")
	w("  | jq -r 'to_entries[] | \"%s \\(.key) --body \\(.value)\"' \\", varCmd)
	w("  | sh")
	w("```")
	w("")
	if bp.VCS == "github" {
		w("Also create the GitHub *environments* (dev, stg, prd) under repo Settings →")
		w("Environments — the OIDC subjects bind to them, and prd's required-reviewer")
		w("gate lives there on plans that support it (DESIGN §11.3).")
	} else {
		w("Also mark the default branch protected and configure the prd environment under")
		w("Settings → CI/CD; deployment approvals enforce on Premium/Ultimate (§11.3).")
	}
	w("")
	w("## 4. Verify")
	w("")
	w("Push a no-op change under `infra/`: the infra pipeline should stop reporting")
	w("\"bootstrap pending\" and produce a real plan (V1). Until this succeeds, treat")
	w("plan/apply as NOT EXERCISED — V0 never proved deployability (§12).")
	if bp.Cloud == "azure" {
		w("")
		w("## Azure notes")
		w("")
		w("- Kubernetes lanes: publish the `external_secrets_client_id` output into the")
		w("  `neckbeard-cluster-vars` ConfigMap in flux-system (Flux substitutes it into")
		w("  the controllers layer).")
		w("- Encryption-at-host needs the subscription feature registered once:")
		w("  `az feature register --namespace Microsoft.Compute --name EncryptionAtHost`.")
	}
	return []byte(b.String())
}
