package render

import (
	"fmt"
	"strings"

	"github.com/bealesh/neckbeard/core/blueprint"
	"github.com/bealesh/neckbeard/core/ownership"
)

// bootstrapFiles renders infra/bootstrap/<env>/ — the one root a human applies
// with elevated credentials, once per environment (DESIGN §10.3): state backend,
// CI OIDC federation, plan/apply identities. These roots keep LOCAL state; the
// runbook says so and treats the state files as operator artifacts.
func bootstrapFiles(bp *blueprint.Blueprint, l lane, opts Options) []ownership.File {
	var files []ownership.File
	for _, env := range bp.Environments {
		dir := "infra/bootstrap/" + env.Name
		files = append(files,
			ownership.File{Path: dir + "/providers.tf", Content: l.providers(bp, env), Owner: ownership.OwnerGenerated},
			ownership.File{Path: dir + "/main.tf", Content: bootstrapMainTF(bp, env, opts), Owner: ownership.OwnerGenerated},
			ownership.File{Path: dir + "/outputs.tf", Content: bootstrapOutputsTF(bp), Owner: ownership.OwnerGenerated},
		)
	}
	files = append(files, ownership.File{Path: "docs/bootstrap.md", Content: bootstrapRunbook(bp), Owner: ownership.OwnerGenerated})
	return files
}

func bootstrapMainTF(bp *blueprint.Blueprint, env blueprint.Environment, opts Options) []byte {
	mod := blueprint.ModuleUsage{Source: "catalog/" + bp.Cloud + "/bootstrap"}
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Bootstrap keeps LOCAL state on purpose (it creates the backend everything\n# else uses); treat terraform.tfstate here as an operator artifact — see\n# docs/bootstrap.md.\n\n")
	lines := []kv{
		{"source", fmt.Sprintf("%q", moduleSource(opts, bp, mod))},
		{"name_prefix", fmt.Sprintf("%q", fmt.Sprintf("%s-%s-%s", bp.Org, bp.App, env.Name))},
		{"region", fmt.Sprintf("%q", bp.Region)},
		{"environment", fmt.Sprintf("%q", env.Name)},
		{"vcs", fmt.Sprintf("%q", bp.VCS)},
		{"repo", fmt.Sprintf("%q", bp.Repo)},
	}
	if bp.Cloud == "aws" {
		b.WriteString("variable \"existing_oidc_provider_arn\" {\n  type    = string\n  default = null\n}\n\n")
		lines = append(lines, kv{"existing_oidc_provider_arn", "var.existing_oidc_provider_arn"})
	}
	if bp.Cloud == "aws" || bp.Cloud == "azure" {
		b.WriteString("variable \"github_subject_prefix\" {\n  type    = string\n  default = null\n}\n\n")
		lines = append(lines, kv{"github_subject_prefix", "var.github_subject_prefix"})
	}
	fmt.Fprintf(&b, "module \"bootstrap\" {\n%s}\n", alignKV(lines, 2))
	return []byte(b.String())
}

func bootstrapOutputsTF(bp *blueprint.Blueprint) []byte {
	text := generatedHeader + `output "backend_hcl" {
  description = "Write to infra/envs/<env>/backend.hcl and commit it."
  value       = module.bootstrap.backend_hcl
}

output "ci_variables" {
  description = "Set these as CI variables (docs/bootstrap.md has the exact commands)."
  value       = module.bootstrap.ci_variables
}

output "release_store" {
  description = "Versioned storage for deployment receipts; configure-ci records its location."
  value       = module.bootstrap.release_store
}
`
	if bp.Cloud == "aws" || bp.Cloud == "azure" {
		text += "\noutput \"github_subject_prefix\" {\n  value = module.bootstrap.github_subject_prefix\n}\n"
	}
	return []byte(text)
}

func bootstrapRunbook(bp *blueprint.Blueprint) []byte {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	login := map[string]string{
		"aws":   "credentials for THAT environment's AWS account exported (e.g. `aws sso login` / env vars); admin-equivalent IAM",
		"gcp":   "`gcloud auth application-default login` against THAT environment's project; Owner-equivalent IAM",
		"azure": "`az login` with rights on THAT environment's subscription: Owner (role assignments are created) plus Entra Application Administrator (flexible federated identity credentials)",
	}[bp.Cloud]

	w("# Bootstrap runbook — %s", bp.App)
	w("")
	w("> Generated by neckbeard. One-time, per environment, run by a human with")
	w("> elevated credentials (DESIGN §10.3). Complete initial resource and secret")
	w("> setup below before handing delivery to federated CI identities.")
	w("")
	w("Repeat the steps below once per environment (dev, stg, prd).")
	w("This configures the repository OIDC subject template for neckbeard; existing cloud trust must use the same template.")
	if bp.Cloud == "aws" {
		w("For environments in the same account, the first bootstrap owns the OIDC provider. Pass its ARN as existing_oidc_provider_arn to later bootstrap roots; never import one provider into multiple states.")
	}
	w("")
	w("## 0. Credentials")
	w("")
	w("You need %s.", login)
	if bp.Cloud == "gcp" {
		w("Enable the required project APIs before applying; this requires Service Usage Admin. Replace <project> with this environment's project ID:")
		w("```sh")
		w("gcloud services enable compute.googleapis.com run.googleapis.com sqladmin.googleapis.com servicenetworking.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com container.googleapis.com iam.googleapis.com iamcredentials.googleapis.com sts.googleapis.com cloudresourcemanager.googleapis.com cloudscheduler.googleapis.com --project <project>")
		w("```")
	}
	w("")
	w("## 1. Apply the bootstrap root")
	w("")
	if bp.VCS == "github" && (bp.Cloud == "aws" || bp.Cloud == "azure") {
		w("Before planning, record GitHub's exact repository subject prefix. New repositories include immutable owner/repository IDs; do not replace them with names or wildcards:")
		w("```sh")
		w("gh api repos/%s/actions/oidc/customization/sub --jq '{github_subject_prefix: .sub_claim_prefix}' > infra/bootstrap/<env>/identity.auto.tfvars.json", bp.Repo)
		w("```")
		w("Review and retain that non-secret input. The prefix must identify this exact repository. Legacy repositories may use `repo:owner/name`.")
	}
	w("```sh")
	w("tofu -chdir=infra/bootstrap/<env> init")
	w("tofu -chdir=infra/bootstrap/<env> apply")
	w("```")
	w("")
	w("This root keeps **local state** (it creates the backend everything else uses).")
	w("Keep `infra/bootstrap/<env>/terraform.tfstate` safe like a credential: it is the")
	w("recovery handle for the backend and CI trust. Re-running apply is idempotent;")
	w("after a partial failure, re-run — it continues rather than recreating.")
	w("")
	w("## 2. Wire the environment backend")
	w("")
	w("```sh")
	w("tofu -chdir=infra/bootstrap/<env> output -raw backend_hcl > infra/envs/<env>/backend.hcl")
	w("git add infra/envs/<env>/backend.hcl && git commit -m 'bootstrap: <env> backend'")
	w("```")
	w("")
	w("## 3. Prepare the deployment foundations")
	w("")
	w("Use credentials scoped to this environment for this initial setup. It creates the network, registry, secret containers and optional object storage before an application image exists. Kubernetes lanes also create their cluster and nodes; these incur compute costs even before apps run.")
	w("```sh")
	w("neckbeard release foundation-plan -env <env>")
	w("# Review the saved plan and its resource costs before continuing.")
	w("neckbeard release foundation-apply -env <env>")
	w("```")
	w("The foundation step permits creates only. Updates, replacements, deletions and application workloads require the full infrastructure workflow. A partial apply can be re-planned; existing resources stay in state.")
	if bp.DatabaseSecret != "" {
		w("")
		w("For this managed PostgreSQL database, prepare its connection before the full infrastructure apply:")
		w("```sh")
		w("neckbeard release prepare-database -env <env>")
		w("```")
		w("This creates the database and stores its connection in %s. The first attempt saves a random password in the cloud secret before applying; retries reuse it. Secret values never enter local files, plans or state. A failed setup leaves a pending connection that the infrastructure runner refuses to deploy. Run one setup at a time per environment.", bp.DatabaseSecret)
		if bp.Cloud == "gcp" {
			w("The setup operator needs Secret Manager Secret Accessor and Secret Version Adder on this connection secret. Grant the CI apply service account Secret Manager Admin on each declared application secret: it needs secret-level IAM administration to install runtime access grants, as well as read access for the database connection. Scope the grants to those secrets, not the project. Project IAM Admin does not grant secret-level IAM administration. The PR plan identity needs none of these roles.")
		}
		if bp.Cloud == "azure" {
			w("Before the first CI infrastructure apply, grant its service principal Key Vault Secrets User on this environment's vault so it can read the prepared connection. The PR plan identity does not need secret access. The vault's initial Secrets Officer assignment stays with the setup operator when subsequent applies run as CI; replace that assignment explicitly if the operator changes.")
		}
		if bp.Cloud == "aws" {
			w("Fresh generated AWS databases use the application connection password and do not enable RDS-managed automatic password rotation. Existing RDS-managed databases require an explicit credential migration; this create-only helper refuses updates.")
		}
	}
	w("")
	w("## 4. Set the CI variables")
	w("")
	if bp.VCS == "github" {
		w("First create the GitHub environments (dev, stg, prd). Production requires required reviewers with self-review disabled; private repositories need a plan that supports that rule. `configure-ci -env prd` refuses a missing rule before publishing production variables.")
	} else {
		w("First protect the default branch and configure the protected prd environment with required deployment approvals (Premium/Ultimate). `configure-ci -env prd` refuses a missing approval rule before publishing production variables.")
	}
	w("Keep those platform rules enabled afterward and verify them with an independent approver; configuration checks do not prove a successful approval path.")
	w("")
	w("After the registry exists, publish its URL and the bootstrap outputs directly:")
	w("")
	w("```sh")
	w("neckbeard release configure-ci -env <env>")
	w("git add .neckbeard/deploy/<env>.store.json")
	w("```")
	w("Commit the non-secret store location with the backend configuration. Release jobs restore and save verified deployment receipts in this versioned cloud storage; CI artifact expiration does not remove rollback history.")
	w("")
	w("### The plan identity's trust boundary, stated plainly")
	w("")
	w("Pull-request pipelines run code the PR authored — the OpenTofu configuration under `infra/` and the release runner sources under `.neckbeard/release/` — with the **plan** identity. That is safe for the same reason planning PR-modified HCL is safe, and only for that reason: the plan identity is read-only, cannot write state, and has no secret-value access, and PR plans substitute a public placeholder for the database password. Do not grant the plan identity anything beyond what bootstrap created; a wider plan role turns every pull request into a deployment.")
	if bp.VCS == "github" {
		w("")
		w("PR plan jobs bind the `<env>-plan` GitHub environments (the OIDC trust names them exactly). Their first run creates them unprotected — leave them that way: a protection rule on a `-plan` environment blocks pull-request plans, and approval belongs on the deploy environments (`dev`, `stg`, `prd`), not on read-only plans. Fork pull requests receive no OIDC token at all and degrade to validate-only.")
	}
	w("")
	w("## 5. Verify")
	w("")
	w("Push a no-op change under `infra/`: the infra pipeline should stop reporting")
	w("\"bootstrap pending\" and produce a real plan (V1). Until this succeeds, treat")
	w("plan/apply as NOT EXERCISED — V0 never proved deployability (§12).")
	if bp.Cloud == "azure" {
		w("")
		w("## Azure notes")
		w("")
		w("- Kubernetes lanes: publish the `external_secrets_client_id` output into the")
		w("  `neckbeard-cluster-vars` ConfigMap in flux-system (Flux substitutes it into")
		w("  the controllers layer).")
		w("- Encryption-at-host needs the subscription feature registered once:")
		w("  `az feature register --namespace Microsoft.Compute --name EncryptionAtHost`.")
	}
	return []byte(b.String())
}
