package render

import (
	"fmt"
	"strings"

	"github.com/bealesh/neckbeard/core/blueprint"
	"github.com/bealesh/neckbeard/core/ownership"
)

// k8sDelivery renders the clusters/ layer for kubernetes lanes: a kustomize base
// of app manifests, per-env overlays with digest pins, and Flux delivery —
// Kustomization CRs per env, image automation into dev, PR-based digest bumps for
// stg/prd (DESIGN §11.2).
//
// Delivered here: namespaces, deployments, services, cronjobs, ingress, Flux CRs.
// NOT here yet (in-cluster controllers layer, next increment): the
// aws-load-balancer-controller HelmRelease that makes Ingress real, and
// external-secrets to materialize the app secret. Pods reference the secret and
// stay Pending until it exists — fail-closed, not silently unconfigured.
func k8sDelivery(bp *blueprint.Blueprint) []ownership.File {
	files := []ownership.File{
		{Path: "clusters/base/apps/kustomization.yaml", Content: baseKustomization(bp), Owner: ownership.OwnerGenerated},
		{Path: "clusters/base/apps/namespace.yaml", Content: namespaceYAML(bp), Owner: ownership.OwnerGenerated},
	}
	for _, s := range bp.Services {
		switch s.Kind {
		case "http":
			files = append(files,
				ownership.File{Path: "clusters/base/apps/deployment-" + s.Name + ".yaml", Content: deploymentYAML(bp, s), Owner: ownership.OwnerGenerated},
				ownership.File{Path: "clusters/base/apps/service-" + s.Name + ".yaml", Content: serviceYAML(bp, s), Owner: ownership.OwnerGenerated},
				ownership.File{Path: "clusters/base/apps/ingress-" + s.Name + ".yaml", Content: ingressYAML(bp, s), Owner: ownership.OwnerGenerated},
			)
		case "worker":
			files = append(files,
				ownership.File{Path: "clusters/base/apps/deployment-" + s.Name + ".yaml", Content: deploymentYAML(bp, s), Owner: ownership.OwnerGenerated},
			)
		case "cron":
			files = append(files,
				ownership.File{Path: "clusters/base/apps/cronjob-" + s.Name + ".yaml", Content: cronJobYAML(bp, s), Owner: ownership.OwnerGenerated},
			)
		}
	}
	for _, env := range bp.Environments {
		files = append(files,
			ownership.File{Path: "clusters/" + env.Name + "/apps.yaml", Content: fluxKustomizationYAML(bp, env.Name), Owner: ownership.OwnerGenerated},
			ownership.File{Path: "clusters/" + env.Name + "/apps/kustomization.yaml", Content: envKustomization(bp, env.Name), Owner: ownership.OwnerGenerated},
		)
		if env.Name == "dev" {
			// Image automation commits fresh digests to dev only; stg/prd move by
			// promotion PR (§11.2).
			files = append(files, ownership.File{Path: "clusters/dev/image-automation.yaml", Content: imageAutomationYAML(bp), Owner: ownership.OwnerGenerated})
		}
	}
	return files
}

const generatedYAMLManifestHeader = "# Generated by neckbeard — do not edit. Regeneration refuses modified files;\n# change neckbeard.yaml or app-profile.yaml and re-run plan + scaffold.\n"

// placeholderImage keeps manifests deployable-shaped before the first release;
// Flux image automation (dev) and promotion PRs (stg/prd) own the real digests.
// The kustomize images transformer matches on the tag-less repo name.
const (
	placeholderRepo  = "public.ecr.aws/docker/library/busybox"
	placeholderImage = placeholderRepo + ":stable"
)

func appNS(bp *blueprint.Blueprint) string { return bp.App }

func namespaceYAML(bp *blueprint.Blueprint) []byte {
	return fmt.Appendf(nil, `%sapiVersion: v1
kind: Namespace
metadata:
  name: %s
  labels:
    managed-by: neckbeard
`, generatedYAMLManifestHeader, appNS(bp))
}

func baseKustomization(bp *blueprint.Blueprint) []byte {
	var b strings.Builder
	b.WriteString(generatedYAMLManifestHeader)
	b.WriteString("apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n  - namespace.yaml\n")
	for _, s := range bp.Services {
		switch s.Kind {
		case "http":
			fmt.Fprintf(&b, "  - deployment-%s.yaml\n  - service-%s.yaml\n  - ingress-%s.yaml\n", s.Name, s.Name, s.Name)
		case "worker":
			fmt.Fprintf(&b, "  - deployment-%s.yaml\n", s.Name)
		case "cron":
			fmt.Fprintf(&b, "  - cronjob-%s.yaml\n", s.Name)
		}
	}
	return []byte(b.String())
}

func containerYAML(bp *blueprint.Blueprint, s blueprint.Service, indent string) string {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, indent+f+"\n", a...) }
	w("- name: %s", s.Name)
	w("  image: %s # {\"$imagepolicy\": \"flux-system:%s\"}", placeholderImage, bp.App)
	arg := map[string]string{"http": "serve", "worker": "work", "cron": "report"}[s.Kind]
	w("  args: [%q]", arg)
	w("  securityContext:")
	w("    allowPrivilegeEscalation: false")
	w("    readOnlyRootFilesystem: true")
	w("    runAsNonRoot: true")
	w("    capabilities:")
	w("      drop: [\"ALL\"]")
	w("  resources:")
	w("    requests: { cpu: 250m, memory: 256Mi }")
	w("    limits: { cpu: \"1\", memory: 1Gi }")
	// The secret is materialized by external-secrets (controllers layer, next):
	// until then pods stay Pending — fail-closed by design.
	w("  envFrom:")
	w("    - secretRef:")
	w("        name: %s-secrets", bp.App)
	if s.Kind == "http" {
		w("  ports:")
		w("    - containerPort: %d", s.Port)
		w("  readinessProbe:")
		w("    httpGet: { path: %s, port: %d }", s.HealthPath, s.Port)
		w("  livenessProbe:")
		w("    httpGet: { path: %s, port: %d }", s.HealthPath, s.Port)
		w("    initialDelaySeconds: 10")
	}
	return b.String()
}

func deploymentYAML(bp *blueprint.Blueprint, s blueprint.Service) []byte {
	replicas := 1
	return fmt.Appendf(nil, `%sapiVersion: apps/v1
kind: Deployment
metadata:
  name: %s
  namespace: %s
spec:
  replicas: %d
  selector:
    matchLabels:
      app: %s
  template:
    metadata:
      labels:
        app: %s
    spec:
      containers:
%s`, generatedYAMLManifestHeader, s.Name, appNS(bp), replicas, s.Name, s.Name, containerYAML(bp, s, "        "))
}

func serviceYAML(bp *blueprint.Blueprint, s blueprint.Service) []byte {
	return fmt.Appendf(nil, `%sapiVersion: v1
kind: Service
metadata:
  name: %s
  namespace: %s
spec:
  selector:
    app: %s
  ports:
    - port: 80
      targetPort: %d
`, generatedYAMLManifestHeader, s.Name, appNS(bp), s.Name, s.Port)
}

func ingressYAML(bp *blueprint.Blueprint, s blueprint.Service) []byte {
	return fmt.Appendf(nil, `%s# Requires the aws-load-balancer-controller (controllers layer, next increment):
# until it is installed this Ingress is inert — no ALB is created.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: %s
  namespace: %s
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: %s
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: %s
                port:
                  number: 80
`, generatedYAMLManifestHeader, s.Name, appNS(bp), s.HealthPath, s.Name)
}

func cronJobYAML(bp *blueprint.Blueprint, s blueprint.Service) []byte {
	return fmt.Appendf(nil, `%sapiVersion: batch/v1
kind: CronJob
metadata:
  name: %s
  namespace: %s
spec:
  schedule: %q
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
%s`, generatedYAMLManifestHeader, s.Name, appNS(bp), s.Schedule, containerYAML(bp, s, "            "))
}

func envKustomization(bp *blueprint.Blueprint, env string) []byte {
	return fmt.Appendf(nil, `%sapiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apps
images:
  # The release flow owns this pin: Flux image automation rewrites it on dev;
  # stg/prd move only via promotion PRs bumping the digest (DESIGN §11.2).
  - name: %s
    newTag: bootstrap-pending
`, generatedYAMLManifestHeader, placeholderRepo)
}

func fluxKustomizationYAML(bp *blueprint.Blueprint, env string) []byte {
	prune := "true"
	return fmt.Appendf(nil, `%s# Applied by flux bootstrap --path=clusters/%s (bootstrap docs land with M3).
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: %s-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/%s/apps
  prune: %s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
  wait: true
`, generatedYAMLManifestHeader, env, bp.App, env, prune)
}

func imageAutomationYAML(bp *blueprint.Blueprint) []byte {
	return fmt.Appendf(nil, `%s# Image automation: fresh digests land on dev automatically; stg/prd move only
# via promotion PRs (DESIGN §11.2). The registry URL is completed at bootstrap
# (account-specific) — flux bootstrap docs cover it.
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: %s
  namespace: flux-system
spec:
  image: REGISTRY_URL_FROM_BOOTSTRAP/%s
  interval: 2m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: %s
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: %s
  filterTags:
    pattern: '^[0-9a-f]{40}$' # immutable commit-SHA tags only
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: %s
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: neckbeard-flux
        email: flux@neckbeard.local
      messageTemplate: "dev: image update by Flux image automation"
    push:
      branch: main
  update:
    path: ./clusters/dev
    strategy: Setters
`, generatedYAMLManifestHeader, bp.App, bp.App, bp.App, bp.App, bp.App)
}
