// Package render turns a blueprint into a write-set: a pure function of the
// blueprint, byte-identical on every call (DESIGN §9).
//
// M1 scope: OpenTofu env roots for the aws / serverless-containers lane, plus the
// topology document and user-owned extension points. Unsupported lanes are refused
// by name — never rendered as guesses.
package render

import (
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/bealesh/neckbeard/core/blueprint"
	"github.com/bealesh/neckbeard/core/ownership"
	"github.com/bealesh/neckbeard/core/pipeline"
)

type Options struct {
	// CatalogSource is the base for module sources: a go-getter git base
	// ("git::https://…/neckbeard.git", pinned to ref=catalog-v<version>) or a local
	// path for development and tests.
	CatalogSource string
}

// DefaultCatalogSource pins module sources to the catalog repo at the blueprint's
// catalog version.
const DefaultCatalogSource = "git::https://github.com/bealesh/neckbeard.git"

// WriteSet renders the blueprint into files for ownership.Apply.
func WriteSet(bp *blueprint.Blueprint, opts Options) ([]ownership.File, error) {
	if opts.CatalogSource == "" {
		opts.CatalogSource = DefaultCatalogSource
	}
	if bp.Cloud != "aws" || bp.Runtime != "serverless-containers" {
		return nil, fmt.Errorf("rendering for lane %s/%s is not implemented yet — M1 covers aws/serverless-containers first; the planner accepted your blueprint and no files were written", bp.Cloud, bp.Runtime)
	}

	model, err := pipeline.Build(bp)
	if err != nil {
		return nil, err
	}

	files := []ownership.File{
		{Path: "docs/topology.md", Content: topologyDoc(bp), Owner: ownership.OwnerGenerated},
		{Path: ".neckbeard/hooks/test.sh", Content: testHookStub(), Owner: ownership.OwnerUser, Mode: 0o755},
	}
	switch bp.VCS {
	case "github":
		files = append(files,
			ownership.File{Path: ".github/workflows/neckbeard-ci.yml", Content: pipeline.RenderGitHubCI(model), Owner: ownership.OwnerGenerated},
			ownership.File{Path: ".github/workflows/neckbeard-infra.yml", Content: pipeline.RenderGitHubInfra(model), Owner: ownership.OwnerGenerated},
		)
	case "gitlab":
		files = append(files,
			ownership.File{Path: ".gitlab-ci.yml", Content: pipeline.RenderGitLab(model), Owner: ownership.OwnerGenerated},
		)
	default:
		return nil, fmt.Errorf("unknown vcs %q in blueprint", bp.VCS)
	}
	for _, env := range bp.Environments {
		dir := "infra/envs/" + env.Name
		files = append(files,
			ownership.File{Path: dir + "/backend.tf", Content: backendTF(), Owner: ownership.OwnerGenerated},
			ownership.File{Path: dir + "/providers.tf", Content: providersTF(bp, env.Name), Owner: ownership.OwnerGenerated},
			ownership.File{Path: dir + "/main.tf", Content: mainTF(bp, env, opts), Owner: ownership.OwnerGenerated},
			ownership.File{Path: dir + "/outputs.tf", Content: outputsTF(env), Owner: ownership.OwnerGenerated},
			ownership.File{Path: dir + "/custom.tf", Content: customTFStub(env.Name), Owner: ownership.OwnerUser},
		)
	}
	return files, nil
}

const generatedHeader = "# Generated by neckbeard — do not edit. Regeneration refuses modified files;\n# change neckbeard.yaml or app-profile.yaml and re-run plan + scaffold.\n# Additions belong in custom.tf (user-owned, never regenerated).\n\n"

func backendTF() []byte {
	return []byte(generatedHeader + `terraform {
  # Partial backend configuration: bucket, key, region, and locking are supplied at
  # init time from bootstrap outputs (M2/M3): tofu init -backend-config=…
  # V0 static validation initializes with -backend=false.
  backend "s3" {}
}
`)
}

func providersTF(bp *blueprint.Blueprint, envName string) []byte {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("terraform {\n  required_version = \">= 1.8.0\"\n\n  required_providers {\n")
	for _, p := range bp.Pins.Providers {
		name := p.Name[strings.LastIndex(p.Name, "/")+1:]
		fmt.Fprintf(&b, "    %s = {\n      source  = %q\n      version = %q\n    }\n", name, p.Name, p.Version)
	}
	b.WriteString("  }\n}\n\n")
	fmt.Fprintf(&b, `provider "aws" {
  region = %q

  default_tags {
    tags = {
      "neckbeard-app" = %q
      "neckbeard-env" = %q
      "managed-by"    = "neckbeard"
    }
  }
}
`, bp.Region, bp.App, envName)
	return []byte(b.String())
}

// mainTF wires the env's modules together. The wiring knowledge is per-lane and
// lives here, not in the agent: renderers are deterministic code (DESIGN §7).
func mainTF(bp *blueprint.Blueprint, env blueprint.Environment, opts Options) []byte {
	present := map[string]blueprint.ModuleUsage{}
	for _, m := range env.Modules {
		present[m.Name] = m
	}

	var b strings.Builder
	b.WriteString(generatedHeader)

	if _, ok := present["runtime-serverless"]; ok {
		b.WriteString(servicesLocal(bp.Services))
		b.WriteString("\n")
	}

	// Emission order is readability (dependency-ish) order; determinism comes from
	// it being fixed.
	wiring := map[string][]kv{
		"dns-ingress": {
			{"vpc_id", "module.network.vpc_id"},
			{"public_subnet_ids", "module.network.public_subnet_ids"},
			{"http_services", `[for s in local.services : { name = s.name, port = s.port, health_path = s.health_path } if s.kind == "http"]`},
		},
		"runtime-serverless": {
			{"services", "local.services"},
			{"vpc_id", "module.network.vpc_id"},
			{"private_subnet_ids", "module.network.private_subnet_ids"},
			{"alb_security_group_id", "module.dns_ingress.alb_security_group_id"},
			{"target_group_arns", "module.dns_ingress.target_group_arns"},
			{"secret_arns", "module.secrets.secret_arns"},
		},
		"postgres": {
			{"vpc_id", "module.network.vpc_id"},
			{"private_subnet_ids", "module.network.private_subnet_ids"},
			{"allowed_security_group_ids", "[module.runtime_serverless.service_security_group_id]"},
		},
	}
	// Wiring lines that reference absent modules are dropped (e.g. secrets not needed).
	requires := map[string]string{
		"module.network.":            "network",
		"module.dns_ingress.":        "dns-ingress",
		"module.runtime_serverless.": "runtime-serverless",
		"module.secrets.":            "secrets",
		"local.services":             "runtime-serverless",
	}

	for _, name := range []string{"network", "dns-ingress", "runtime-serverless", "postgres", "storage", "secrets", "registry"} {
		mod, ok := present[name]
		if !ok {
			continue
		}
		lines := []kv{{"source", strconv.Quote(moduleSource(opts, bp, mod))}}
		for _, in := range mod.Inputs {
			lines = append(lines, kv{in.Key, hclValue(in.Value)})
		}
		for _, w := range wiring[name] {
			missing := false
			for prefix, dep := range requires {
				if strings.Contains(w.v, prefix) {
					if _, have := present[dep]; !have {
						missing = true
					}
				}
			}
			if !missing {
				lines = append(lines, w)
			}
		}
		rest := lines[1:] // keep source first, sort the assignments
		sort.SliceStable(rest, func(i, j int) bool { return rest[i].k < rest[j].k })
		fmt.Fprintf(&b, "module %q {\n%s}\n\n", hclLabel(name), alignKV(lines, 2))
	}
	return []byte(strings.TrimRight(b.String(), "\n") + "\n")
}

func servicesLocal(services []blueprint.Service) string {
	var b strings.Builder
	b.WriteString("locals {\n  services = [\n")
	for _, s := range services {
		lines := []kv{
			{"name", strconv.Quote(s.Name)},
			{"kind", strconv.Quote(s.Kind)},
			{"port", strconv.Itoa(s.Port)},
			{"health_path", strconv.Quote(s.HealthPath)},
			{"schedule", strconv.Quote(s.Schedule)},
		}
		b.WriteString("    {\n" + alignKV(lines, 6) + "    },\n")
	}
	b.WriteString("  ]\n}\n")
	return b.String()
}

func outputsTF(env blueprint.Environment) []byte {
	present := map[string]bool{}
	for _, m := range env.Modules {
		present[m.Name] = true
	}
	type out struct{ name, module, expr, desc string }
	candidates := []out{
		{"alb_dns_name", "dns-ingress", "module.dns_ingress.alb_dns_name", "Public entry point (HTTP, M1)"},
		{"cluster_name", "runtime-serverless", "module.runtime_serverless.cluster_name", "ECS cluster running the services"},
		{"db_endpoint", "postgres", "module.postgres.endpoint", "PostgreSQL endpoint (credentials: RDS-managed secret)"},
		{"db_master_user_secret_arn", "postgres", "module.postgres.master_user_secret_arn", "RDS-managed master credentials secret"},
		{"bucket_name", "storage", "module.storage.bucket_name", "Application object storage"},
		{"registry_url", "registry", "module.registry.repository_url", "Container registry (immutable tags)"},
	}
	var b strings.Builder
	b.WriteString(generatedHeader)
	for _, c := range candidates {
		if present[c.module] {
			fmt.Fprintf(&b, "output %q {\n  description = %q\n  value       = %s\n}\n\n", c.name, c.desc, c.expr)
		}
	}
	return []byte(strings.TrimRight(b.String(), "\n") + "\n")
}

func moduleSource(opts Options, bp *blueprint.Blueprint, mod blueprint.ModuleUsage) string {
	if strings.HasPrefix(opts.CatalogSource, "git::") {
		return fmt.Sprintf("%s//%s?ref=catalog-v%s", opts.CatalogSource, mod.Source, bp.Pins.Catalog)
	}
	return path.Join(opts.CatalogSource, mod.Source)
}

type kv struct{ k, v string }

// alignKV renders `key = value` lines padded the way tofu fmt aligns a block of
// consecutive assignments, so rendered files are fmt-clean by construction.
func alignKV(lines []kv, indent int) string {
	width := 0
	for _, l := range lines {
		if len(l.k) > width {
			width = len(l.k)
		}
	}
	var b strings.Builder
	for _, l := range lines {
		fmt.Fprintf(&b, "%s%-*s = %s\n", strings.Repeat(" ", indent), width, l.k, l.v)
	}
	return b.String()
}

func hclLabel(moduleName string) string {
	return strings.ReplaceAll(moduleName, "-", "_")
}

func hclValue(v any) string {
	switch t := v.(type) {
	case string:
		return strconv.Quote(t)
	case bool:
		return strconv.FormatBool(t)
	case int:
		return strconv.Itoa(t)
	case int64:
		return strconv.FormatInt(t, 10)
	case float64:
		return strconv.FormatFloat(t, 'f', -1, 64)
	case []string:
		quoted := make([]string, len(t))
		for i, s := range t {
			quoted[i] = strconv.Quote(s)
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	case []any:
		parts := make([]string, len(t))
		for i, e := range t {
			parts[i] = hclValue(e)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	default:
		// The blueprint schema restricts values to scalars and string arrays; anything
		// else is a planner bug and must fail loudly at render time.
		panic(fmt.Sprintf("unrenderable blueprint value %T (%v)", v, v))
	}
}

func testHookStub() []byte {
	return []byte(`#!/usr/bin/env sh
# .neckbeard/hooks/test.sh — user-owned test hook, run by the generated CI test job.
# neckbeard created this file once and will never regenerate it.
#
# Replace the lines below with your real test command(s), e.g.:
#   go test ./...        or        mix test        or        npm test
echo "neckbeard test hook: no tests configured yet — edit .neckbeard/hooks/test.sh"
exit 0
`)
}

func customTFStub(env string) []byte {
	return fmt.Appendf(nil, `# custom.tf — user extension point for the %s environment.
#
# neckbeard created this file once and will never regenerate or delete it.
# Resources declared here live alongside the generated stack. Prefer a catalog
# override in neckbeard.yaml for anything the catalog supports; use this file for
# what it does not.
`, env)
}

func topologyDoc(bp *blueprint.Blueprint) []byte {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# Topology — %s\n\n", bp.App)
	w("> Generated by neckbeard from blueprint `%s`. Do not edit: regeneration will\n", bp.Hash)
	w("> refuse to overwrite a modified copy. Change `neckbeard.yaml` or\n")
	w("> `app-profile.yaml` and re-run `neckbeard plan && neckbeard scaffold` instead.\n\n")

	w("| | |\n|---|---|\n")
	w("| app | `%s` (org `%s`) |\n", bp.App, bp.Org)
	w("| cloud / region | %s / %s |\n", bp.Cloud, bp.Region)
	w("| runtime | %s |\n", bp.Runtime)
	w("| VCS | %s |\n", bp.VCS)
	w("| tier | %s |\n", bp.Tier)
	w("| pins | catalog %s · opentofu %s · planner %s |\n\n", bp.Pins.Catalog, bp.Pins.OpenTofu, bp.Pins.Planner)

	if len(bp.Services) > 0 {
		w("## Services\n\n| service | kind | port | health | schedule |\n|---|---|---|---|---|\n")
		for _, s := range bp.Services {
			w("| %s | %s | %s | %s | %s |\n", s.Name, s.Kind, orDash(s.Port), orDashS(s.HealthPath), orDashS(s.Schedule))
		}
		w("\n")
	}

	for _, env := range bp.Environments {
		w("## Environment: %s\n\n", env.Name)
		w("| module | version | inputs |\n|---|---|---|\n")
		for _, m := range env.Modules {
			var parts []string
			for _, in := range m.Inputs {
				s := fmt.Sprintf("%s=%v", in.Key, in.Value)
				switch in.Provenance {
				case "override-supported":
					s += " (override)"
				case "override-warned":
					s += " (override, outside tested envelope)"
				}
				parts = append(parts, s)
			}
			w("| %s | %s | %s |\n", m.Name, m.Version, strings.Join(parts, ", "))
		}
		w("\n")
	}

	if len(bp.References) > 0 {
		w("## External references (not provisioned)\n\n")
		for _, r := range bp.References {
			w("- **%s** — existing service, consumed via secret `%s`; neckbeard does not manage its lifecycle\n", r.Capability, r.SecretName)
		}
		w("\n")
	}
	if len(bp.Warnings) > 0 {
		w("## Warnings\n\n")
		for _, warning := range bp.Warnings {
			w("- %s\n", warning)
		}
	}
	return []byte(b.String())
}

func orDash(i int) string {
	if i == 0 {
		return "—"
	}
	return strconv.Itoa(i)
}

func orDashS(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
