// Package render turns a blueprint into a write-set: a pure function of the
// blueprint, byte-identical on every call (DESIGN §9).
//
// M0 scope: the topology document and the user-owned extension points. The real
// OpenTofu roots, pipelines, and delivery layouts land in M1 — render grows, the
// ownership contract around it does not change.
package render

import (
	"fmt"
	"strings"

	"github.com/bealesh/neckbeard/core/blueprint"
	"github.com/bealesh/neckbeard/core/ownership"
)

// WriteSet renders the blueprint into files for ownership.Apply.
func WriteSet(bp *blueprint.Blueprint) []ownership.File {
	files := []ownership.File{
		{Path: "docs/topology.md", Content: topologyDoc(bp), Owner: ownership.OwnerGenerated},
	}
	for _, env := range bp.Environments {
		files = append(files, ownership.File{
			Path:    fmt.Sprintf("infra/envs/%s/custom.tf", env.Name),
			Content: customTFStub(env.Name),
			Owner:   ownership.OwnerUser,
		})
	}
	return files
}

func customTFStub(env string) []byte {
	return fmt.Appendf(nil, `# custom.tf — user extension point for the %s environment.
#
# neckbeard created this file once and will never regenerate or delete it.
# Resources declared here live alongside the generated stack. Prefer a catalog
# override in neckbeard.yaml for anything the catalog supports; use this file for
# what it does not.
`, env)
}

func topologyDoc(bp *blueprint.Blueprint) []byte {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# Topology — %s\n\n", bp.App)
	w("> Generated by neckbeard from blueprint `%s`. Do not edit: regeneration will\n", bp.Hash)
	w("> refuse to overwrite a modified copy. Change `neckbeard.yaml` or\n")
	w("> `app-profile.yaml` and re-run `neckbeard plan && neckbeard scaffold` instead.\n\n")

	w("| | |\n|---|---|\n")
	w("| app | `%s` (org `%s`) |\n", bp.App, bp.Org)
	w("| cloud / region | %s / %s |\n", bp.Cloud, bp.Region)
	w("| runtime | %s |\n", bp.Runtime)
	w("| VCS | %s |\n", bp.VCS)
	w("| tier | %s |\n", bp.Tier)
	w("| pins | catalog %s · opentofu %s · planner %s |\n\n", bp.Pins.Catalog, bp.Pins.OpenTofu, bp.Pins.Planner)

	for _, env := range bp.Environments {
		w("## Environment: %s\n\n", env.Name)
		w("| module | version | inputs |\n|---|---|---|\n")
		for _, m := range env.Modules {
			var parts []string
			for _, in := range m.Inputs {
				s := fmt.Sprintf("%s=%v", in.Key, in.Value)
				switch in.Provenance {
				case "override-supported":
					s += " (override)"
				case "override-warned":
					s += " (override, outside tested envelope)"
				}
				parts = append(parts, s)
			}
			w("| %s | %s | %s |\n", m.Name, m.Version, strings.Join(parts, ", "))
		}
		w("\n")
	}

	if len(bp.References) > 0 {
		w("## External references (not provisioned)\n\n")
		for _, r := range bp.References {
			w("- **%s** — existing service, consumed via secret `%s`; neckbeard does not manage its lifecycle\n", r.Capability, r.SecretName)
		}
		w("\n")
	}
	if len(bp.Warnings) > 0 {
		w("## Warnings\n\n")
		for _, warning := range bp.Warnings {
			w("- %s\n", warning)
		}
	}
	return []byte(b.String())
}
